#!/bin/sh

set -euvx

readonly this="$(readlink -f "$0")"
readonly whatami="$(basename "${this}")"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$@"
    exit 1
}

# take nothing and detect the installed ros_distro; print ros_distro on
# success; print nothing on failure
detect_ros_distro() {
    if ! [ -d /opt/ros ]; then
        error "missing directory: /opt/ros"
        return 1
    fi
    # shellcheck disable=SC2039
    local result=""
    result="$(find /opt/ros -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort | xargs)"
    if [ -z "${result}" ]; then
        error "missing ROS installation"
        return 1
    fi
    if ! [ "${result##* }" = "${result}" ]; then
        warning "multiple ROS installations: ${result}"
    fi
    echo "${result##* }"
    return 0
}

vet_catkin_ws() {
    # shellcheck disable=SC2039
    local result=""
    if ! result="$(readlink -f "$1")"; then
        error "bad path: $1"
        return 1
    fi
    if ! [ -d "${result}" ]; then
        error "not a directory: ${result}"
        return 1
    fi
    if ! [ -d "${result}/src" ]; then
        error "not a directory: ${result}/src"
        return 1
    fi
    echo "${result}"
    return 0
}

# double check test arguments are valid packages and tunnels into directory 
# arguments for packages
expand_package_args() {
    if [ -z "${TARGET_TEST_ARGS}" ]; then
      error "No test arguments were provided"
    fi

    local new_pkg_args=""
    for pkg_arg in $TARGET_TEST_ARGS; do
      if [ $(catkin locate ${pkg_arg}) ]; then
          new_pkg_args="${pkg_arg} ${new_pkg_args}"
          continue
      fi

      info "Cannot locate package [${pkg_arg}], checking directories.."
      pkg_arg_dir=$(find "${CATKIN_WS}/src" -name "${pkg_arg}")
      info "${pkg_arg_dir}"
      if [ -d "${pkg_arg_dir}" ]; then
          local child_args="$(ls ${pkg_arg_dir})"
          info ${child_args}
          
          for child_pkg_arg in ${child_args}; do
            if [ $(catkin locate ${child_pkg_arg}) ]; then
                  new_pkg_args="${child_pkg_arg} ${new_pkg_args}"
              fi
          done
      else
          die "Cannot locate directory [${pkg_arg}]. Bad arguments."
      fi
    done
    info ${new_pkg_args}
    TARGET_TEST_ARGS=${new_pkg_args}
}

################################################################################

# catkin_ws
if [ -n "${CATKIN_WS:-}" ]; then
    info "CATKIN_WS: ${CATKIN_WS}"
else
    if ! CATKIN_WS="$(vet_catkin_ws "${PWD}")"; then
        die "failure: vet_catkin_ws ${PWD}"
    fi
    readonly CATKIN_WS="${CATKIN_WS}"
    warning "defaulting CATKIN_WS: ${CATKIN_WS}"
fi

if [ -n "${ROS_DISTRO:-}" ]; then
    info "seen ROS_DISTRO: ${ROS_DISTRO}"
elif ROS_DISTRO="$(detect_ros_distro)"; then
    export ROS_DISTRO
    warning "detected ROS_DISTRO: ${ROS_DISTRO}"
else
    die "failed to get and/or detect ROS_DISTRO"
fi


cd ${CATKIN_WS}
catkin config --init --install --extend "/opt/ros/${ROS_DISTRO}"

TARGET_TEST_ARGS="$@"
expand_package_args
info "Test Tags: ${TARGET_TEST_ARGS}"

# Can run with '--no-deps' if we specify the packages we want to build
EXTRA_TEST_ARGS=""
if [ -n "${TARGET_TEST_ARGS}" ]; then
  EXTRA_TEST_ARGS="--no-deps"
fi

info "[TEST BUILD]"
catkin build ${TARGET_TEST_ARGS} \
    -w ${CATKIN_WS} \
    -c \
    --no-color \
    --no-notify \
    --no-status \
    --summarize \
    --verbose \
    --cmake-args \
    -DCMAKE_CPP_FLAGS="${CPPFLAGS:-}" \
    -DCMAKE_CXX_COMPILER="${CXX:-$(command -v c++)}" \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS:-}" \
    -DCMAKE_C_COMPILER="${CC:-$(command -v cc)}" \
    -DCMAKE_C_FLAGS="${CFLAGS:-}" \
    -DCMAKE_VERBOSE_MAKEFILE=true \
    --make-args \
    "${MAKEFLAGS:- --jobs=$(((3 + $(nproc)) / 4)) --load-average=$(($(nproc) / 2))}" \
    && info "[BUILD SUCCESS]" \
    || die "[BUILD FAIL]"

info "[TEST RUN]"
set +euvx
. ${CATKIN_WS}/devel/setup.sh --extend
. /opt/ros/${ROS_DISTRO}/setup.sh --extend
set -euvx

catkin run_tests ${TARGET_TEST_ARGS} \
    --workspace ${CATKIN_WS} \
    ${EXTRA_TEST_ARGS} \
    --no-color \
    --no-notify \
    --no-status \
    --summarize \
    --verbose \
    --make-args \
    --jobs=1 \
    && info "[TEST SUCCESS]" \
    || warning "[TEST FAIL]"

set +euvx
# shellcheck disable=SC1090
. ${CATKIN_WS}/install/setup.sh
set -euvx

info "[TEST RESULTS]"
catkin_test_results --all --verbose ${CATKIN_WS}/build/
